const menu = [
  {
    id: 1,
    title: "Pork Potstickers ",
    category: "Appetizers",
    price: 6.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 2,
    title: "Vegetable Spring Roll",
    category: "Appetizers",
    price: 1.5,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 3,
    title: "Fried Egg Roll",
    category: "Appetizers",
    price: 3.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 4,
    title: "Honey Chicken",
    category: "Entrees",
    price: 5.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 5,
    title: "Moo Goo Gai Pan",
    category: "Entrees",
    price: 6.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 6,
    title: "Hunan chicken",
    category: "Entrees",
    price: 5.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 7,
    title: "Vegetable Soup",
    category: "Entrees",
    price: 5.5,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 8,
    title: "Seafood Soup",
    category: "Entrees",
    price: 7.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 9,
    title: "Eggdrop Soup",
    category: "Entrees",
    price: 7.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 10,
    title: "The Golden Dragon",
    category: "Cocktails",
    price: 14.5,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 11,
    title: "Cranberry Martini",
    category: "Cocktails",
    price: 10.5,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 12,
    title: "Hawaiian Breeze",
    category: "Cocktails",
    price: 12.5,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 13,
    title: "Pineapple Kiwi",
    category: "Cocktails",
    price: 11.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 14,
    title: "Rum Wave",
    category: "Cocktails",
    price: 12.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
  {
    id: 15,
    title: "Strawberry Mango",
    category: "Cocktails",
    price: 10.25,
    description: "Lorem ipsum dolor sit amet, consetetur",
  },
];

export default menu;
